# Generated by Django 2.1.5 on 2019-01-22 21:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190123_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='Write in the format of longitude and latitude.', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
